project_id = "cmugqctuyqsimhfxruap"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.notify-dispatch]
    verify_jwt = false
  [functions.push-subscribe]
    verify_jwt = false
